libselinux-python: Add native support
Source: meta-selinux
MR: 234607
Type: Integration
Disposition: Merged from meta-selinux
ChangeID: 30a49ab1298d2a081089a9e4c760a9e02f8100f6
Description:

Add native support for libselinux-python
to fix build error for setools-native

ERROR: Nothing RPROVIDES 'libselinux-python-native'
(but virtual:native: meta-selinux/recipes-security/setools/setools_4.5.1.bb
RDEPENDS on or otherwise requires it)

Signed-off-by: Poonam Jadhav <poonam.jadhav@kpit.com>
Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>